'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import type { Profile, StudentDetails, ModuleRow, Stage } from '@/lib/types'
import { careerSuggestions, dimensions, quizQuestions, stageOrder, stagePlans, subjectNames, type DimensionKey } from '@/lib/guidance'
import { getSupabaseBrowser } from '@/lib/supabase-browser'
import SafeMarkdown from './SafeMarkdown'

type Props={profile:Profile;onSignOut:()=>void}
type Assessment={id:string;kind:'profile'|'swot';payload:Record<string,unknown>;scores:Record<string,number>;created_at:string}
type Subject={id:string;subject_name:string;score:number|null;enjoyment:number|null;confidence:number|null;notes:string|null}
type Assignment={id:string;status:string;due_date:string|null;completed_at:string|null;learning_modules:ModuleRow|null}
type Action={id:string;title:string;notes:string|null;due_date:string|null;status:string}
type Institution={id:string;name:string;institution_type:string;country:string;website_url:string;admissions_url:string|null;notes:string|null}
type Appointment={id:string;requested_start:string|null;confirmed_start:string|null;duration_minutes:number;topic:string;student_message:string|null;staff_response:string|null;status:string}
type Settings={portal_name:string;organisation_name:string;counsellor_name:string;counsellor_email:string|null;booking_provider:string;booking_url:string|null;welcome_message:string}

function fmt(d:string|null){return d?new Date(d).toLocaleString():''}

export default function StudentPortal({profile,onSignOut}:Props){
  const supabase=useMemo(()=>getSupabaseBrowser(),[])
  const [tab,setTab]=useState('dashboard'); const [loading,setLoading]=useState(true); const [message,setMessage]=useState('')
  const [details,setDetails]=useState<StudentDetails|null>(null); const [assessments,setAssessments]=useState<Assessment[]>([]); const [subjects,setSubjects]=useState<Subject[]>([]); const [assignments,setAssignments]=useState<Assignment[]>([]); const [actions,setActions]=useState<Action[]>([]); const [institutions,setInstitutions]=useState<Institution[]>([]); const [appointments,setAppointments]=useState<Appointment[]>([]); const [settings,setSettings]=useState<Settings|null>(null); const [openModule,setOpenModule]=useState<Assignment|null>(null)
  useEffect(()=>{void refresh()},[])
  async function refresh(){setLoading(true); const uid=profile.id; const [d,a,s,m,p,i,ap,st]=await Promise.all([
    supabase.from('student_details').select('*').eq('user_id',uid).maybeSingle(),
    supabase.from('assessment_results').select('*').eq('student_id',uid).order('created_at',{ascending:false}),
    supabase.from('subject_results').select('*').eq('student_id',uid).order('subject_name'),
    supabase.from('module_assignments').select('id,status,due_date,completed_at,learning_modules(id,slug,category,title,summary,content_md,external_url,is_published)').eq('student_id',uid).order('assigned_at',{ascending:false}),
    supabase.from('action_plans').select('*').eq('student_id',uid).order('created_at',{ascending:false}),
    supabase.from('institutions').select('*').eq('active',true).order('name'),
    supabase.from('appointments').select('*').eq('student_id',uid).order('created_at',{ascending:false}),
    supabase.from('portal_settings').select('*').eq('id',true).maybeSingle()
  ]); setDetails(d.data as StudentDetails|null);setAssessments((a.data||[]) as Assessment[]);setSubjects((s.data||[]) as Subject[]);setAssignments((m.data||[]) as unknown as Assignment[]);setActions((p.data||[]) as Action[]);setInstitutions((i.data||[]) as Institution[]);setAppointments((ap.data||[]) as Appointment[]);setSettings(st.data as Settings|null);setLoading(false)}
  const profileResult=assessments.find(x=>x.kind==='profile'); const swot=assessments.find(x=>x.kind==='swot');
  const suggestions=careerSuggestions(profileResult?.scores||null,subjects.map(s=>({name:s.subject_name,score:s.score})))
  const completion=assignments.length?Math.round(assignments.filter(a=>a.status==='completed').length/assignments.length*100):0
  const stage=(details?.stage||'Form 1') as Stage
  const nav=[['dashboard','Overview'],['roadmap','Roadmap'],['assessments','Assessments & SWOT'],['subjects','Subjects & Careers'],['learning','Learning Hub'],['plan','My Action Plan'],['appointments','Counselling'],['institutions','Universities & TVET']]
  return <div className="portal-shell"><aside className="sidebar"><div className="sidebar-brand"><div className="brand-mark small">P</div><div><strong>{settings?.portal_name||'Pathways'}</strong><span>Student Portal</span></div></div><nav>{nav.map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</nav><div className="sidebar-user"><strong>{profile.full_name}</strong><span>{stage}</span><button onClick={onSignOut}>Sign out</button></div></aside>
  <main className="portal-main"><header className="topbar"><div><p className="eyebrow">PATHWAYS • {stage.toUpperCase()}</p><h1>{nav.find(n=>n[0]===tab)?.[1]}</h1></div><div className="status-pill">{completion}% learning complete</div></header>{message&&<div className="notice success">{message}</div>}{loading?<div className="card">Loading your pathway…</div>:<>
  {tab==='dashboard'&&<Dashboard/>}{tab==='roadmap'&&<Roadmap/>}{tab==='assessments'&&<Assessments/>}{tab==='subjects'&&<Subjects/>}{tab==='learning'&&<Learning/>}{tab==='plan'&&<Plan/>}{tab==='appointments'&&<Appointments/>}{tab==='institutions'&&<Institutions/>}</>}</main>
  {openModule&&<div className="modal-backdrop" onMouseDown={()=>setOpenModule(null)}><div className="modal-card" onMouseDown={e=>e.stopPropagation()}><div className="card-head"><div><p className="eyebrow">{openModule.learning_modules?.category}</p><h2>{openModule.learning_modules?.title}</h2></div><button className="icon-button" onClick={()=>setOpenModule(null)}>×</button></div><SafeMarkdown text={openModule.learning_modules?.content_md||''}/>{openModule.learning_modules?.external_url&&<a className="primary inline-button" href={openModule.learning_modules.external_url} target="_blank" rel="noreferrer">Open authorised external resource ↗</a>}<div className="btn-row"><button className="primary" onClick={()=>completeModule(openModule.id)}>Mark completed</button><button className="secondary" onClick={()=>setOpenModule(null)}>Close</button></div></div></div>}</div>

  function Dashboard(){return <><section className="hero"><div><p className="eyebrow">WELCOME BACK</p><h2>Hello, {profile.full_name.split(' ')[0]}.</h2><p>{settings?.welcome_message}</p><div className="pill-list"><span className="tag teal">{stagePlans[stage].theme}</span><span className="tag">{details?.career_focus||'Exploring'}</span></div></div><div className="hero-stat"><strong>{completion}%</strong><span>assigned learning complete</span></div></section><section className="grid four section-gap"><Metric label="Current stage" value={stage}/><Metric label="Profile" value={profileResult?topProfile(profileResult.scores):'Not completed'}/><Metric label="Subjects recorded" value={String(subjects.length)}/><Metric label="Actions done" value={`${actions.filter(a=>a.status==='done').length}/${actions.length}`}/></section><section className="grid two section-gap"><div className="card"><p className="eyebrow">THIS STAGE</p><h3>{stagePlans[stage].theme}</h3>{stagePlans[stage].goals.map(g=><div className="action-line" key={g}>✓ <span>{g}</span></div>)}</div><div className="card"><p className="eyebrow">NEXT CONVERSATION</p><h3>Turn exploration into a decision</h3><p>Use your assessment results, subject evidence and shortlist as discussion material with your counsellor.</p><button className="primary" onClick={()=>setTab('appointments')}>Book or request counselling</button></div></section></>}
  function Roadmap(){return <section className="timeline">{stageOrder.map((s,i)=><article className={`card timeline-card ${s===stage?'current':''}`} key={s}><div className="timeline-number">{i+1}</div><div><div className="card-head"><div><p className="eyebrow">{s===stage?'CURRENT STAGE':i<stageOrder.indexOf(stage)?'FOUNDATION':'AHEAD'}</p><h3>{s}: {stagePlans[s].theme}</h3></div></div>{stagePlans[s].goals.map(g=><div className="action-line" key={g}>• <span>{g}</span></div>)}</div></article>)}</section>}
  function Assessments(){return <div className="stack"><QuizCard/><SwotCard/></div>}
  function QuizCard(){const [answers,setAnswers]=useState<Record<number,number>>({}); async function save(){const scores:Record<DimensionKey,number>={analytical:0,creative:0,people:0,business:0,practical:0,digital:0};quizQuestions.forEach((q,i)=>scores[q[1]]+=(answers[i]||3)); const {error}=await supabase.from('assessment_results').insert({student_id:profile.id,kind:'profile',payload:{version:1,answers},scores}); if(!error){setMessage('Career profile saved.');await refresh()}}
    return <section className="card"><p className="eyebrow">PATHWAYS PROFILE</p><h3>Interests & working preferences</h3><p className="muted">Rate each statement from 1 (not like me) to 5 (very much like me). This guides discussion; it is not a psychological diagnosis.</p>{profileResult&&<ProfileBars scores={profileResult.scores}/>}<details><summary>{profileResult?'Retake profile':'Start the 18-question profile'}</summary><div className="quiz-list">{quizQuestions.map((q,i)=><div className="quiz-question" key={i}><strong>{i+1}. {q[0]}</strong><div className="scale">{[1,2,3,4,5].map(n=><button key={n} className={(answers[i]||3)===n?'selected':''} onClick={()=>setAnswers(v=>({...v,[i]:n}))}>{n}</button>)}</div></div>)}</div><button className="primary" onClick={save}>Save my profile</button></details></section>}
  function SwotCard(){const p=(swot?.payload||{}) as Record<string,string>; const [v,setV]=useState({strengths:p.strengths||'',weaknesses:p.weaknesses||'',opportunities:p.opportunities||'',threats:p.threats||''}); async function save(e:FormEvent){e.preventDefault();const {error}=await supabase.from('assessment_results').insert({student_id:profile.id,kind:'swot',payload:v,scores:{}});if(!error){setMessage('SWOT saved.');await refresh()}}
    return <section className="card"><p className="eyebrow">GUIDED SWOT</p><h3>My current learning SWOT</h3><form className="grid two" onSubmit={save}><label>Strengths<textarea value={v.strengths} onChange={e=>setV({...v,strengths:e.target.value})} placeholder="Subjects, habits, skills and qualities that currently help you"/></label><label>Growth areas<textarea value={v.weaknesses} onChange={e=>setV({...v,weaknesses:e.target.value})} placeholder="Skills, habits or subjects needing support"/></label><label>Opportunities<textarea value={v.opportunities} onChange={e=>setV({...v,opportunities:e.target.value})} placeholder="Clubs, mentors, courses, scholarships or work exposure"/></label><label>Obstacles / threats<textarea value={v.threats} onChange={e=>setV({...v,threats:e.target.value})} placeholder="Time, confidence, access, finances, grades or other barriers"/></label><div><button className="primary">Save SWOT</button></div></form></section>}
  function Subjects(){const [name,setName]=useState('Mathematics');const [score,setScore]=useState('');const [enjoyment,setEnjoyment]=useState('3'); async function save(e:FormEvent){e.preventDefault();const {error}=await supabase.from('subject_results').upsert({student_id:profile.id,subject_name:name,score:score===''?null:Number(score),enjoyment:Number(enjoyment),confidence:Number(enjoyment)},{onConflict:'student_id,subject_name'});if(!error){setMessage('Subject evidence saved.');setScore('');await refresh()}}
    return <><section className="grid two"><div className="card"><p className="eyebrow">SUBJECT EVIDENCE</p><h3>Add or update a subject</h3><form onSubmit={save}><label>Subject<select value={name} onChange={e=>setName(e.target.value)}>{subjectNames.map(s=><option key={s}>{s}</option>)}</select></label><label>Current mark (%)<input type="number" min="0" max="100" value={score} onChange={e=>setScore(e.target.value)} placeholder="Optional"/></label><label>How much do you enjoy it? <select value={enjoyment} onChange={e=>setEnjoyment(e.target.value)}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n}/5</option>)}</select></label><button className="primary">Save subject</button></form></div><div className="card"><p className="eyebrow">MY SUBJECTS</p><h3>Current picture</h3>{subjects.length?subjects.map(s=><div className="list-row" key={s.id}><div><strong>{s.subject_name}</strong><span>Enjoyment {s.enjoyment||'–'}/5</span></div><strong>{s.score==null?'–':`${s.score}%`}</strong></div>):<p className="muted">No subjects recorded yet.</p>}</div></section><section className="section-gap"><p className="eyebrow">CAREER DIRECTIONS TO EXPLORE</p><div className="grid three">{suggestions.slice(0,6).map(s=><article className="card" key={s.key}><span className="tag teal">{s.label}</span><h3>{s.careers.slice(0,3).join(' • ')}</h3><p>{s.description}</p><p className="small"><strong>Useful subjects:</strong> {s.subjects.join(', ')}</p><p className="fineprint">Subject requirements differ by institution and programme. Always verify current admissions information.</p></article>)}</div></section></>}
  function Learning(){return <section><div className="card-head"><div><p className="eyebrow">ASSIGNED BY YOUR COUNSELLOR</p><h3>Learning Hub</h3></div><span className="status-pill">{assignments.filter(a=>a.status==='completed').length}/{assignments.length} complete</span></div><div className="grid two">{assignments.length?assignments.map(a=><article className="card" key={a.id}><div className="card-head"><span className="tag">{a.learning_modules?.category}</span><span className={`tag ${a.status==='completed'?'teal':''}`}>{a.status}</span></div><h3>{a.learning_modules?.title}</h3><p>{a.learning_modules?.summary}</p>{a.due_date&&<p className="small"><strong>Due:</strong> {a.due_date}</p>}<button className="secondary" onClick={()=>setOpenModule(a)}>Open module</button></article>):<div className="card"><p>No modules have been assigned yet.</p></div>}</div></section>}
  function Plan(){const [title,setTitle]=useState('');const [due,setDue]=useState('');async function add(e:FormEvent){e.preventDefault();if(!title.trim())return;const {error}=await supabase.from('action_plans').insert({student_id:profile.id,title:title.trim(),due_date:due||null,created_by:profile.id});if(!error){setTitle('');setDue('');setMessage('Action added.');await refresh()}}async function status(id:string,status:string){await supabase.from('action_plans').update({status}).eq('id',id);await refresh()}
    return <section className="grid two"><div className="card"><p className="eyebrow">NEXT STEPS</p><h3>My action plan</h3>{actions.length?actions.map(a=><div className="list-row" key={a.id}><div><strong>{a.title}</strong><span>{a.due_date?`Due ${a.due_date}`:'No due date'} • {a.status.replace('_',' ')}</span></div><select value={a.status} onChange={e=>status(a.id,e.target.value)}><option value="open">Open</option><option value="in_progress">In progress</option><option value="done">Done</option></select></div>):<p className="muted">Start with one small, specific action.</p>}</div><div className="card"><p className="eyebrow">ADD ACTION</p><form onSubmit={add}><label>What will you do?<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Example: Compare two engineering programmes"/></label><label>Target date<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><button className="primary">Add to my plan</button></form></div></section>}
  function Appointments(){const [topic,setTopic]=useState('Career pathway review');const [when,setWhen]=useState('');const [note,setNote]=useState('');async function request(e:FormEvent){e.preventDefault();const {error}=await supabase.from('appointments').insert({student_id:profile.id,requested_start:when?new Date(when).toISOString():null,topic,student_message:note||null});if(!error){setMessage('Counselling request sent.');setWhen('');setNote('');await refresh()}}async function cancel(id:string){await supabase.rpc('cancel_my_appointment',{p_appointment_id:id});await refresh()}
    return <section className="grid two"><div className="card"><p className="eyebrow">GUIDANCE & COUNSELLING</p><h3>Request an appointment</h3><form onSubmit={request}><label>Topic<input value={topic} onChange={e=>setTopic(e.target.value)}/></label><label>Preferred date and time<input type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)}/></label><label>What would you like to discuss?<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><button className="primary">Send request</button></form>{settings?.booking_url&&<div className="callout"><strong>External booking:</strong><p>Your counsellor also provides a {settings.booking_provider} booking page.</p><a className="secondary inline-button" href={settings.booking_url} target="_blank" rel="noreferrer">Open booking calendar ↗</a></div>}{settings?.counsellor_email&&<p className="small">Email: <a href={`mailto:${settings.counsellor_email}`}>{settings.counsellor_email}</a></p>}</div><div className="card"><p className="eyebrow">MY APPOINTMENTS</p><h3>Requests and meetings</h3>{appointments.length?appointments.map(a=><div className="appointment" key={a.id}><div className="card-head"><strong>{a.topic}</strong><span className="tag">{a.status}</span></div><p className="small">Requested: {fmt(a.requested_start)||'Flexible'}</p>{a.confirmed_start&&<p><strong>Confirmed:</strong> {fmt(a.confirmed_start)}</p>}{a.staff_response&&<p>{a.staff_response}</p>}{['requested','confirmed'].includes(a.status)&&<button className="link-button" onClick={()=>cancel(a.id)}>Cancel request</button>}{a.confirmed_start&&<CalendarLinks appointment={a}/>}</div>):<p className="muted">No appointment requests yet.</p>}</div></section>}
  function Institutions(){return <section><div className="card"><p className="eyebrow">VERIFY CURRENT REQUIREMENTS</p><h3>Universities, colleges and technical pathways</h3><p>Use these as starting points. Admission criteria, programme availability, deadlines and funding can change, so always check the institution’s current official information before making a decision.</p></div><div className="grid two section-gap">{institutions.map(i=><article className="card" key={i.id}><span className="tag teal">{i.institution_type}</span><h3>{i.name}</h3><p>{i.notes}</p><div className="btn-row"><a className="secondary inline-button" href={i.website_url} target="_blank" rel="noreferrer">Website ↗</a>{i.admissions_url&&<a className="primary inline-button" href={i.admissions_url} target="_blank" rel="noreferrer">Admissions ↗</a>}</div></article>)}</div></section>}
  async function completeModule(id:string){const {error}=await supabase.rpc('complete_my_module',{p_assignment_id:id});if(!error){setMessage('Module marked complete.');setOpenModule(null);await refresh()}}
}

function Metric({label,value}:{label:string;value:string}){return <div className="card metric-card"><span>{label}</span><strong>{value}</strong></div>}
function topProfile(scores:Record<string,number>){return Object.entries(scores).sort((a,b)=>b[1]-a[1]).slice(0,2).map(([k])=>dimensions[k as DimensionKey].label).join(' + ')}
function ProfileBars({scores}:{scores:Record<string,number>}){return <div className="profile-bars"><h4>{topProfile(scores)}</h4>{Object.entries(scores).sort((a,b)=>b[1]-a[1]).map(([k,v])=><div className="bar-row" key={k}><span>{dimensions[k as DimensionKey].label}</span><div className="bar"><i style={{width:`${Math.round(v/15*100)}%`}}/></div><strong>{v}/15</strong></div>)}</div>}
function CalendarLinks({appointment}:{appointment:Appointment}){if(!appointment.confirmed_start)return null;const start=new Date(appointment.confirmed_start);const end=new Date(start.getTime()+appointment.duration_minutes*60000);const stamp=(d:Date)=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const title=encodeURIComponent(`Pathways counselling: ${appointment.topic}`);const dates=`${stamp(start)}/${stamp(end)}`;const google=`https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&dates=${dates}`;const outlook=`https://outlook.office.com/calendar/0/deeplink/compose?subject=${title}&startdt=${encodeURIComponent(start.toISOString())}&enddt=${encodeURIComponent(end.toISOString())}`;return <div className="btn-row"><a className="secondary inline-button" href={google} target="_blank" rel="noreferrer">Add to Google Calendar</a><a className="secondary inline-button" href={outlook} target="_blank" rel="noreferrer">Add to Outlook</a></div>}
